### ISSUE TITLE
Your link has been hijacked pointing to porn site?!

### ISSUE THREAD

**Issue by joe-oli** [krasimir/jolly-roger#9]
Your link on the right hand side has been hijacked pointing to porn site?!
`https://poet.codes/etc...`

**Comment by krasimir** [comment]
Yep, someone bought the domain after it expired and used it for ... let's say some other stuff. I updated links where I found them. The new place of Poet is https://poet.krasimir.now.sh/. Can you point me to a url where you saw such `poet.codes` refereces.

**Comment by krasimir** [comment]
Ah I saw it :) stupid me. Fixed. The correct URL is https://poet.krasimir.now.sh/e/mq2PoRVJ4CG/frame/1300px/930px
